#!/usr/bin/env bash
set -e

echo 'export TERM=screen' >> ~/.bashrc
echo 'export PATH="~/.local/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

sudo bash -c 'echo 127.0.0.1 `hostname` >> /etc/hosts'

ISSUE=$(cat /etc/issue | head -n 1)

sudo apt-get update
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
sudo apt-get install -y \
    htop \
    tcpdump \
    iotop \
    tmux \
    mtr \
    mosh \
    iftop \
    python-pip \
    msr-tools \
    silversearcher-ag \
    emacs24 \
    vim \
    zsh \
    clang \
    libclang-dev \
    llvm \
    llvm-dev \
    ocaml \
    opam \
    irssi \
    binutils-multiarch \
    git \
    mercurial

JDK_MAJOR=8
JDK_MINOR=74
JDK_BUILD=02

JDK_VERSION="$JDK_MAJOR""u$JDK_MINOR"
JDK_PATH="$HOME/jdk1.$JDK_MAJOR.0_$JDK_MINOR"
if [ ! -d "$JDK_PATH" ]; then
    wget -c --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/$JDK_VERSION-b$JDK_BUILD/jdk-$JDK_VERSION-linux-x64.tar.gz" --output-document="jdk-$JDK_VERSION-linux-x64.tar.gz"
    tar xvzf jdk-$JDK_VERSION-linux-x64.tar.gz
fi

pip install --user ipython

if [ ! -f /dev/mem ]; then
    sudo mknod -m 660 /dev/mem c 1 1
    sudo chown root:kmem /dev/mem
fi
if [ ! -f /dev/kmem ]; then
    sudo mknod -m 640 /dev/kmem c 1 2
    sudo chown root:kmem /dev/kmem
fi
if [ ! -f /dev/port ]; then
    sudo mknod -m 660 /dev/port c 1 4
    sudo chown root:mem /dev/port
fi
